FROM base-rust

RUN apt-get install -y python git make g++

WORKDIR /build
RUN git clone --recursive https://github.com/rust-lang/rust
WORKDIR /build/rust
RUN ./configure --prefix=/rust \
                --target=arm-linux-androideabi \
                --arm-linux-androideabi-ndk=/android/ndk-arm
RUN make -j10
RUN make install

RUN apt-get install -y libssl-dev cmake

WORKDIR /build
RUN git clone --recursive https://github.com/rust-lang/cargo
WORKDIR /build/cargo
RUN ./configure --prefix=/rust --enable-optimize
RUN make
RUN make install

RUN rm -rf /build
WORKDIR /home/rustbuild
