FROM base-rust

RUN apt-get install -y python

WORKDIR /build
RUN git clone --recursive https://github.com/rust-lang/rust
WORKDIR /build/rust
RUN ./configure --musl-root=/musl --prefix=/rust \
                --target=x86_64-unknown-linux-musl
RUN make -j10
RUN make install

RUN curl https://static.rust-lang.org/cargo-dist/cargo-nightly-x86_64-unknown-linux-gnu.tar.gz | \
      tar xzf - -C /rust --strip-components=2 \
        cargo-nightly-x86_64-unknown-linux-gnu/cargo/bin

RUN rm -rf /build
WORKDIR /home/rustbuild
ENV PATH=/rust/bin:$PATH
ENV LD_LIBRARY_PATH=/rust/lib
